{"name":"nyc_taxi_dataflow","ppdf:dataflowId":"5ccf2a26-1560-4888-872a-2e4ff82873dd","ppdf:owner":{"tenantId":"08e06420-c505-4a4e-b259-e7ceee464ce8","userId":"821220ee-4f8f-45e7-a08e-35177556f4e9"},"ppdf:fastCopy":true,"version":"1.0","culture":"fr-FR","modifiedTime":"2025-03-11T15:30:15.553246+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"stagging_schema nyctaxi_yellow":{"queryId":"77686fa0-da3e-4f05-9e7d-a3a600decfc1","queryName":"stagging_schema nyctaxi_yellow","loadEnabled":true},"stagging_schema taxi_zones_lookup":{"queryId":"f8bcd860-e4d2-465d-aab5-b6dd84a28c6a","queryName":"stagging_schema taxi_zones_lookup","loadEnabled":true},"Fusionner":{"queryId":"01e7eb7d-bece-4b03-ae71-dddeca6afa39","queryName":"Fusionner","loadEnabled":true},"table_finale":{"queryId":"47221e00-4b9e-4c1e-8f18-2e7f5421e614","queryName":"table_finale","loadEnabled":true},"table_finale_DataDestination":{"queryId":"113c4b45-464d-4818-ab05-ab97efbbdb91","queryName":"table_finale_DataDestination"},"table_finale_WriteToDataDestination":{"queryId":"c16fda50-060d-4d28-a5b1-a4996c463b1a","queryName":"table_finale_WriteToDataDestination"},"table_finale_TransformForWriteToDataDestination":{"queryId":"533c7b0f-1d58-48d0-9eb6-da08700477f6","queryName":"table_finale_TransformForWriteToDataDestination"},"FastCopyStaging":{"queryId":"a56f2d18-43ba-4885-95c0-33fa1e8f3d32","queryName":"FastCopyStaging"}},"document":"section Section1;\r\nshared #\"stagging_schema nyctaxi_yellow\" = let\r\n  Source = Fabric.Warehouse([]),\r\n  #\"Navigation 1\" = Source{[workspaceId = \"6425bdbf-5310-4f9e-8945-115a2c4a54da\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[warehouseId = \"1e7a7706-3763-4827-9ec9-75a3789991c3\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Schema = \"stagging_schema\", Item = \"nyctaxi_yellow\"]}[Data],\r\n  #\"Colonne conditionnelle insérée\" = Table.AddColumn(#\"Navigation 3\", \"vendor\", each if [VendorID] = 1 then \"Creative Mobile Technologies, LLC\" else if [VendorID] = 2 then \"VeriFone Inc\" else \"Unknown\"),\r\n  #\"Colonnes permutées\" = Table.ReorderColumns(#\"Colonne conditionnelle insérée\", {\"VendorID\", \"vendor\", \"tpep_pickup_datetime\", \"tpep_dropoff_datetime\", \"passenger_count\", \"trip_distance\", \"RatecodeID\", \"store_and_fwd_flag\", \"PULocationID\", \"DOLocationID\", \"payment_type\", \"fare_amount\", \"extra\", \"mta_tax\", \"tip_amount\", \"tolls_amount\", \"improvement_surcharge\", \"total_amount\", \"congestion_surcharge\", \"Airport_fee\"}),\r\n  #\"Type de colonne changé\" = Table.TransformColumnTypes(#\"Colonnes permutées\", {{\"vendor\", type text}}),\r\n  #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Type de colonne changé\", {\"VendorID\", \"Airport_fee\", \"congestion_surcharge\", \"improvement_surcharge\", \"tolls_amount\", \"tip_amount\", \"mta_tax\", \"extra\", \"fare_amount\", \"store_and_fwd_flag\", \"RatecodeID\"}),\r\n  #\"Valeur remplacée\" = Table.ReplaceValue(#\"Colonnes supprimées\", null, 0, Replacer.ReplaceValue, {\"passenger_count\"}),\r\n  #\"Colonne conditionnelle insérée 1\" = Table.AddColumn(#\"Valeur remplacée\", \"payment_method\", each if [payment_type] = 1 then \"Credit card\" else if [payment_type] = 2 then \"Cash\" else if [payment_type] = 3 then \"No Charge\" else if [payment_type] = 4 then \"Dispute\" else if [payment_type] = 5 then \"Unkonwn\" else if [payment_type] = 6 then \"Voided trip\" else \"Unknown\"),\r\n  #\"Type de colonne changé 1\" = Table.TransformColumnTypes(#\"Colonne conditionnelle insérée 1\", {{\"payment_method\", type text}}),\r\n  #\"Colonnes supprimées 1\" = Table.RemoveColumns(#\"Type de colonne changé 1\", {\"payment_type\"})\r\nin\r\n  #\"Colonnes supprimées 1\";\r\nshared #\"stagging_schema taxi_zones_lookup\" = let\r\n  Source = Fabric.Warehouse([]),\r\n  #\"Navigation 1\" = Source{[workspaceId = \"6425bdbf-5310-4f9e-8945-115a2c4a54da\"]}[Data],\r\n  #\"Navigation 2\" = #\"Navigation 1\"{[warehouseId = \"1e7a7706-3763-4827-9ec9-75a3789991c3\"]}[Data],\r\n  #\"Navigation 3\" = #\"Navigation 2\"{[Schema = \"stagging_schema\", Item = \"taxi_zones_lookup\"]}[Data]\r\nin\r\n  #\"Navigation 3\";\r\nshared Fusionner = let\r\n  Source = Table.NestedJoin(#\"stagging_schema nyctaxi_yellow\", {\"PULocationID\"}, #\"stagging_schema taxi_zones_lookup\", {\"LocationID\"}, \"stagging_schema taxi_zones_lookup\", JoinKind.LeftOuter),\r\n  #\"stagging_schema taxi_zones_lookup développé\" = Table.ExpandTableColumn(Source, \"stagging_schema taxi_zones_lookup\", {\"Borough\", \"Zone\"}, {\"Borough\", \"Zone\"}),\r\n  #\"Colonnes renommées\" = Table.RenameColumns(#\"stagging_schema taxi_zones_lookup développé\", {{\"Borough\", \"pickup_borough\"}, {\"Zone\", \"pickup_zone\"}}),\r\n  #\"Colonnes permutées\" = Table.ReorderColumns(#\"Colonnes renommées\", {\"vendor\", \"tpep_pickup_datetime\", \"tpep_dropoff_datetime\", \"passenger_count\", \"trip_distance\", \"PULocationID\", \"pickup_zone\", \"pickup_borough\", \"DOLocationID\", \"total_amount\", \"payment_method\"}),\r\n  #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Colonnes permutées\", {\"PULocationID\"})\r\nin\r\n  #\"Colonnes supprimées\";\r\n[Staging = \"FastCopyStaging\"]\r\nshared table_finale = let\r\n  Source = Table.NestedJoin(Fusionner, {\"DOLocationID\"}, #\"stagging_schema taxi_zones_lookup\", {\"LocationID\"}, \"stagging_schema taxi_zones_lookup\", JoinKind.LeftOuter),\r\n  #\"stagging_schema taxi_zones_lookup développé\" = Table.ExpandTableColumn(Source, \"stagging_schema taxi_zones_lookup\", {\"Borough\", \"Zone\"}, {\"Borough\", \"Zone\"}),\r\n  #\"Colonnes renommées\" = Table.RenameColumns(#\"stagging_schema taxi_zones_lookup développé\", {{\"Borough\", \"dropoff_borough\"}, {\"Zone\", \"dropoff_zone\"}}),\r\n  #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Colonnes renommées\", {\"DOLocationID\"}),\r\n  #\"Colonnes permutées\" = Table.ReorderColumns(#\"Colonnes supprimées\", {\"vendor\", \"tpep_pickup_datetime\", \"tpep_dropoff_datetime\", \"pickup_borough\", \"pickup_zone\", \"dropoff_borough\", \"dropoff_zone\", \"payment_method\", \"passenger_count\", \"trip_distance\", \"total_amount\"}),\r\n  #\"Colonnes renommées 1\" = Table.RenameColumns(#\"Colonnes permutées\", {{\"trip_distance\", \"trip_distcance\"}})\r\nin\r\n  #\"Colonnes renommées 1\";\r\nshared table_finale_DataDestination = let\r\n  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),\r\n  Navigation_1 = Pattern{[workspaceId = \"6425bdbf-5310-4f9e-8945-115a2c4a54da\"]}[Data],\r\n  Navigation_2 = Navigation_1{[warehouseId = \"1e7a7706-3763-4827-9ec9-75a3789991c3\"]}[Data],\r\n  TableNavigation = Navigation_2{[Schema = \"bronze\", Item = \"nyc_taxi_yellow\"]}[Data]\r\nin\r\n  TableNavigation;\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\n[Staging = \"FastCopyStaging\"]\r\nshared table_finale_WriteToDataDestination = let\r\n  table_finale_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = table_finale_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], table_finale_TransformForWriteToDataDestination), Action.DoNothing}))\r\nin\r\n  table_finale_WriteToDataDestination;\r\nshared table_finale_TransformForWriteToDataDestination = let\r\n    ColumnMappings = {[SourceColumnName = \"vendor\", DestinationColumnName = \"vendor\"], [SourceColumnName = \"tpep_pickup_datetime\", DestinationColumnName = \"tpep_pickup_datetime\"], [SourceColumnName = \"tpep_dropoff_datetime\", DestinationColumnName = \"tpep_dropoff_datetime\"], [SourceColumnName = \"pickup_borough\", DestinationColumnName = \"pickup_borough\"], [SourceColumnName = \"pickup_zone\", DestinationColumnName = \"pickup_zone\"], [SourceColumnName = \"dropoff_borough\", DestinationColumnName = \"dropoff_borough\"], [SourceColumnName = \"dropoff_zone\", DestinationColumnName = \"dropoff_zone\"], [SourceColumnName = \"payment_method\", DestinationColumnName = \"payment_method\"], [SourceColumnName = \"passenger_count\", DestinationColumnName = \"passenger_count\"], [SourceColumnName = \"trip_distcance\", DestinationColumnName = \"trip_distance\"], [SourceColumnName = \"total_amount\", DestinationColumnName = \"total_amount\"]},\r\n    SourceColumns = Table.SelectColumns(table_finale, List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\nshared FastCopyStaging = let\r\n  FastCopyStaging = Pipeline.FastCopyModelStorage(DefaultStaging, [Required = false])\r\nin\r\n  FastCopyStaging;\r\n","connectionOverrides":[{"path":"Warehouse","kind":"Warehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Warehouse\",\"path\":\"Warehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"stagging_schema nyctaxi_yellow","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"stagging_schema%20nyctaxi_yellow.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"vendor","dataType":"string"},{"name":"tpep_pickup_datetime","dataType":"dateTime"},{"name":"tpep_dropoff_datetime","dataType":"dateTime"},{"name":"passenger_count","dataType":"double"},{"name":"trip_distance","dataType":"double"},{"name":"PULocationID","dataType":"int64"},{"name":"DOLocationID","dataType":"int64"},{"name":"total_amount","dataType":"double"},{"name":"payment_method","dataType":"string"}]},{"$type":"LocalEntity","name":"stagging_schema taxi_zones_lookup","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"stagging_schema%20taxi_zones_lookup.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"LocationID","dataType":"string"},{"name":"Borough","dataType":"string"},{"name":"Zone","dataType":"string"},{"name":"service_zone","dataType":"string"}]},{"$type":"LocalEntity","name":"Fusionner","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Fusionner.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"vendor","dataType":"string"},{"name":"tpep_pickup_datetime","dataType":"dateTime"},{"name":"tpep_dropoff_datetime","dataType":"dateTime"},{"name":"passenger_count","dataType":"double"},{"name":"trip_distance","dataType":"double"},{"name":"pickup_zone","dataType":"string"},{"name":"pickup_borough","dataType":"string"},{"name":"DOLocationID","dataType":"int64"},{"name":"total_amount","dataType":"double"},{"name":"payment_method","dataType":"string"}]},{"$type":"LocalEntity","name":"table_finale","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"table_finale.parquet"},"annotations":[{"name":"pbi:EntityTypeDisplayHint","value":"CalculatedEntity"},{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"vendor","dataType":"string"},{"name":"tpep_pickup_datetime","dataType":"dateTime"},{"name":"tpep_dropoff_datetime","dataType":"dateTime"},{"name":"pickup_borough","dataType":"string"},{"name":"pickup_zone","dataType":"string"},{"name":"dropoff_borough","dataType":"string"},{"name":"dropoff_zone","dataType":"string"},{"name":"payment_method","dataType":"string"},{"name":"passenger_count","dataType":"double"},{"name":"trip_distcance","dataType":"double"},{"name":"total_amount","dataType":"double"}]}]}